### ISSUE TITLE
Subset the font

### ISSUE THREAD

**Issue by Jack5079** [TheMemeSniper/website#3]
Many of the characters listed on https://fonts.google.com/specimen/Atkinson+Hyperlegible/glyphs you do not use. You can create a subset of the font (I found https://subfonter.net/) without unused glyphs to save space.

**Comment by Jack5079** [comment]
However the font is only the third largest asset, the largest being peggle2.gif, a 24x24 gif that somehow is 84 kb how the fuck does that even happen

**Comment by TheMemeSniper** [comment]
Because the GIF file format is a plague

**Comment by Jack5079** [comment]
I have 28 88x31s on my website, the largest is 8 kb, and the entire page compresses to smaller than peggle2.gif (If I had rich presence off it would be smaller uncompressed too)
![image](https://github.com/TheMemeSniper/website/assets/29169102/d83bbdea-b54c-4e50-b445-1cc4c841455f)

Freeplay's animated 88x31 (which I avoided on my website due to its obscenely large size) is smaller than peggle2.gif
![image](https://github.com/TheMemeSniper/website/assets/29169102/22b9d2ac-580f-4e21-a7cb-2b8b44665314)

I think this is a peggle2.gif issue not a GIF issue

**Comment by Jack5079** [comment]
I have created a version of peggle2 that is 26 kb
![peggle2](https://github.com/TheMemeSniper/website/assets/29169102/2df7310c-ed94-4d10-a201-c2b2960eeb70)

**Comment by TheMemeSniper** [comment]
converting it to webp reduced the filesize to 15.4kb

**Comment by TheMemeSniper** [comment]
fixed in 2d1b67

**Comment by Jack5079** [comment]
HOW
![image](https://github.com/TheMemeSniper/website/assets/29169102/3409bd21-bfb9-43a3-8e29-db26e57ebaad)

**Comment by TheMemeSniper** [comment]
WHAT IN THE FUCK

**Comment by TheMemeSniper** [comment]
actually fixed by 205da2a
