### ISSUE TITLE
​

### ISSUE THREAD

**Issue by Jack5079** [TheMemeSniper/website#5]
![image](https://github.com/TheMemeSniper/website/assets/29169102/a7677801-2a4c-4fce-b5be-2c833b4e064e)

**Comment by TheMemeSniper** [comment]
what

**Comment by nbitzz** [comment]
> what

Jack takes issue with this. That is all

**Comment by Jack5079** [comment]
<img src="https://markojs.com/assets/91bc26e5.svg" width="16"> 🫡
